// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhj4hqGYigv31zjPL-DuSbBMhlNP78eE',
    appId: '1:1078894794898:web:d9e2b4311270a3adf12e4b',
    messagingSenderId: '1078894794898',
    projectId: 'gymnow-eeb97',
    authDomain: 'gymnow-eeb97.firebaseapp.com',
    storageBucket: 'gymnow-eeb97.firebasestorage.app',
    measurementId: 'G-YZ6C5NLZ9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwqOKMj05UpqFXcel7kcq1NdDOO5HIv8E',
    appId: '1:1078894794898:android:58853c16459602a9f12e4b',
    messagingSenderId: '1078894794898',
    projectId: 'gymnow-eeb97',
    storageBucket: 'gymnow-eeb97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEz6sR7cd6rxcyGJyCpGBROw7P56r3IpY',
    appId: '1:1078894794898:ios:717ebaa344c0a220f12e4b',
    messagingSenderId: '1078894794898',
    projectId: 'gymnow-eeb97',
    storageBucket: 'gymnow-eeb97.firebasestorage.app',
    iosBundleId: 'com.example.gymnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEz6sR7cd6rxcyGJyCpGBROw7P56r3IpY',
    appId: '1:1078894794898:ios:717ebaa344c0a220f12e4b',
    messagingSenderId: '1078894794898',
    projectId: 'gymnow-eeb97',
    storageBucket: 'gymnow-eeb97.firebasestorage.app',
    iosBundleId: 'com.example.gymnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFhj4hqGYigv31zjPL-DuSbBMhlNP78eE',
    appId: '1:1078894794898:web:9378df27b027e783f12e4b',
    messagingSenderId: '1078894794898',
    projectId: 'gymnow-eeb97',
    authDomain: 'gymnow-eeb97.firebaseapp.com',
    storageBucket: 'gymnow-eeb97.firebasestorage.app',
    measurementId: 'G-48TXXCS31V',
  );
}
